apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: obdemo-rcs-ui
  annotations:
    cert-manager.io/cluster-issuer: $(CERT_ISSUER)
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      rewrite ^(/rcs)$ $1/ redirect;
spec:
  rules:
  - host: $(FQDN)
    http:
      paths:
      - backend:
          serviceName: obdemo-rcs-ui
          servicePort: 80
        path: /rcs/?(.*)
  tls:
  - hosts:
    - $(FQDN)
    secretName: sslcert
