---
apiVersion: v1
kind: Secret
metadata:
  name: ob-secrets
type: Opaque
data:
 IG_AGENT_ID: {{ .Values.secrets.igAgentID }}
 IG_AGENT_PASSWORD: {{ .Values.secrets.igAgentPassword }}
 IG_CLIENT_ID: {{ .Values.secrets.igClientID }}
 IG_CLIENT_SECRET: {{ .Values.secrets.igClientSecret }}
 IG_IDM_USER: {{ .Values.secrets.igIDMUser }}
 IG_IDM_PASSWORD: {{ .Values.secrets.igIDMPassword }}
 IG_METRICS_PASSWORD: {{ .Values.secrets.igMetricsPassword }}
 IG_METRICS_USERNAME: {{ .Values.secrets.igMetricsUsername }}
 IG_TRUSTSTORE_PASSWORD: {{ .Values.secrets.igTruststorePassword }}
 # Additional OB Config
 IG_OB_ASPSP_SIGNING_KEYSTORE_STOREPASS: {{ .Values.secrets.igOBASPSPSigningKeystoreStorepass }}
 IG_OB_ASPSP_SIGNING_KEYSTORE_KEYPASS: {{ .Values.secrets.igOBASPSPSigningKeystoreKeypass }}
 # Usernames & Passwords for MongoDB - These values must match up to the values in the codefresh env vars within the pipelines
 # Codefresh env var name - MONGOTESTFACILITYUSER
 MONGODB_TEST_FACILITY_USERNAME: {{ .Values.secrets.mongodbTestFacilityUsername }}
 # Codefresh env var name - MONGOTESTFACILITYPASS
 MONGODB_TEST_FACILITY_PASSWORD: {{ .Values.secrets.mongodbTestFacilityPassword }}
 # Codefresh env var name - MONGOCONSENTUSER
 MONGODB_CONSENT_USERNAME: {{ .Values.secrets.mongodbConsentUsername }}
 # Codefresh env var name - MONGOCONSENTPASS
 MONGODB_CONSENT_PASSWORD: {{ .Values.secrets.mongodbConsentPassword }}