apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: obdemo-rcs-api
  annotations:
    cert-manager.io/cluster-issuer: $(CERT_ISSUER)
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/rcs-api)$ $1/ redirect;
spec:
  rules:
  - host: $(FQDN)
    http:
      paths:
      - backend:
          serviceName: obdemo-rcs-api
          servicePort: 8083
        path: /rcs-api/?(.*)
  tls:
  - hosts:
    - $(FQDN)
    secretName: sslcert
