- op: add
  path: /spec/template/spec/initContainers
  value:
    - name: iam-init
      image: eu.gcr.io/sbat-gcr-develop/securebanking/secureopenbanking-uk-fidc-initializer:latest
      imagePullPolicy: Always
      env:
      - name: OPEN_AM_PASSWORD
        valueFrom:
          secretKeyRef:
            name: am-env-secrets
            key: AM_PASSWORDS_AMADMIN_CLEAR
      - name: IAM_FQDN
        valueFrom:
          configMapKeyRef:
            name: platform-config
            key: IAM_FQDN
      - name: REQUEST_BODY_PATH
        value: config/
      command: ["/bin/sh", "-c"]
      args: 
        - |
          until $(curl -X GET --output /dev/null --silent --head --fail -H "X-OpenIDM-Username: anonymous" \
          -H "X-OpenIDM-Password: anonymous" -H "X-OpenIDM-NoSession: true" \
          https://$IAM_FQDN/openidm/info/ping)
          do
          echo "IDM not ready"
          sleep 10
          done
          ./setup
