name: PR - Build Helm
on:
  workflow_dispatch:
  push:
    paths:
      - '_infra/helm/**'
jobs:
  run_pr-helm-template:
    name: PR - Check Helm
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-helm.yml@main
    secrets: inherit
    with:
      componentName: secure-api-gateway-ob-uk
      helmLocation: _infra/helm