name: release-publish-java
run-name: Java Release '${{ inputs.release_version_number }}'
on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      release_tag_ref:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
    secrets:
      FR_ARTIFACTORY_USER:
        required: true
      FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD:
        required: true
jobs:
  build_deploy_java:
    name: Build and deploy java artifact
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        id: checkout_tag
        name: checkout release tag
        with:
          ref: ${{ inputs.release_tag_ref }} # tag created by maven release plugin prepare goal

      # set java and cache
      - uses: actions/setup-java@v3
        id: set_java_maven
        name: set java and maven cache
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_version }}
          architecture: x64
          cache: 'maven'
          server-id: MAVEN_SERVER_ID
          server-username: FR_ARTIFACTORY_USER # env variable for username in deploy
          server-password: FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD # env variable for token in deploy

      - name: Build maven
        run: |
          mvn clean install
        env:
          MAVEN_SERVER_ID: forgerock-private-releases # protected repo id to get the protected dependencies
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

      # Deploy the java artifact
      - name: Deploy release
        id: deploy
        run: |
          mvn clean deploy -Ddockerfile.skip=true
        env:
          MAVEN_SERVER_ID: maven.forgerock.org-community
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}